# Generated by Django 5.0.1 on 2024-04-24 09:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='id',
        ),
        migrations.RemoveField(
            model_name='url',
            name='uuid',
        ),
        migrations.AddField(
            model_name='url',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
